# Generated by Django 5.1.6 on 2025-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='img',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
