# Generated by Django 5.1.6 on 2025-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0002_alter_knowledgebase_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BananaVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('description', models.TextField(help_text='Detailed description of the variety')),
                ('classification', models.CharField(blank=True, help_text='Type or classification of the banana', max_length=255, null=True)),
                ('origin', models.CharField(blank=True, help_text='Geographical origin', max_length=255, null=True)),
                ('harvest_period', models.CharField(blank=True, help_text='Approximate harvest period', max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banana Variety',
                'verbose_name_plural': 'Banana Varieties',
                'db_table': 'escan_banana_varieties',
            },
        ),
    ]
