# Generated by Django 5.1.6 on 2025-11-20 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0003_bananavariety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevalidation',
            name='store_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_validations', to=settings.AUTH_USER_MODEL),
        ),
    ]
