# Generated by Django 5.1.6 on 2025-11-28 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0004_alter_storevalidation_store_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storevalidation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store Validation', 'verbose_name_plural': 'Store Validations'},
        ),
        migrations.AlterField(
            model_name='storevalidation',
            name='store_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_validations', to=settings.AUTH_USER_MODEL),
        ),
    ]
